### ISSUE TITLE
[BUG] იმეილის შეცვლა აქაუნთს ანადგურებს

### ISSUE THREAD

**Issue by Symt4xError** [educata/everrest#105]
- >გვაქ აქაუნთი 1 და 2
- >შევცვლით პირველის მეილს მეორეს მეილით
- >მეორე აქაუნთი მთლად იშლება?
- >შესვლა აღარაა შესაძლებელი პირველის იმეილით
- >ავთენტიკაციის ახალი ტოკენი არ  მოდის მეილის შეცვლისას, ამიტომ /auth წერს "Token contains incorrect user", საჭიროა გამოსვლა.
- >მეორეში შესვლა მეორეს ორიგინალი პაროლით არაა შესაძლებელი, საჭიროა რომ პირველის პაროლი ჩავუწეროთ მეორეს
- >მეორე გადაიქცა პირველად.
- >მეორე აქამდე არიყო ვერიფიცირებული
- >ამის შემდეგ მეორეზე ვერიფიკაციას არ ითხოვს.

მოკლედ, ამ უბრალო მეილის შეცვლით სხვისი ექაუნთის წაშლის და მისი მეილის დაპყრობის საშუალება გვაქვს.

**Comment by CondensedMilk7** [comment]
იმეილის შეცვლის საშუალება წესით არ აქვს მომხმარებელს. რომელ ენდფოინთს იყენებ იმეილის შესაცვლელად?

**Comment by Symt4xError** [comment]
უბრალოდ  /auth/update ვიხმარე. სვაგერშიც არიც იმეილის ველი
![image](https://github.com/educata/everrest/assets/79525322/0e3e2f8e-7993-4184-aa7c-58aba8872b70)

**Comment by KostaD02** [comment]
`auth/update` ენდფოინთში დარჩენილი იყო იმეილის თვისება. ამჟამინდელი განახლებით მომხარებელს აღარ შეუძლია მსგავს ტიპად იმეილის განახლება. იმეილის განახლებისთვის ცალკე იქნება ახალი ენდპოინთი უახლოეს მომავალში.
