### ISSUE TITLE
[FEATURE] || [BUG?] /shop/products/search?keywords მხოლოდ 1 keywordze mushaobs

### ISSUE THREAD

**Issue by Symt4xError** [educata/everrest#106]
/shop/products/search-ს თუ keywords პარამეტრს გავატან მაშინ მხოლოდ 1 სიტყვიან სერჩზე აგდებს შედეგს, სხვა შემთხვევაში უბრალოდ პროდუქტების ობიექტს მიბრუნებს ცარიელი პროდუქტების მასივით

**Comment by Symt4xError** [comment]
![image](https://github.com/educata/everrest/assets/79525322/82f7fc36-9496-41de-8b91-490935bcecaf)

**Comment by KostaD02** [comment]
ძველი სერჩით სიტყვებს იპოვიდა იმ შემთხვევაში თუ მიყოლებით წერია სიტყვები. პირობითად განვიხილოთ შემდგომ პროდუქტებზე:

```js
[
 { title: "Acer Chromebook Spin 513 Convertible Laptop"},
 { title: "ASUS Vivobook Go 15 L510 Thin & Light Laptop Computer" },
 { title: "Lenovo 3i Chromebook" }
]
```

თუ საძიებო სიტყვა იქნებოდა `laptop` , ვალიდური პასუხი იქნებოდა:

```js
[
 { title: "Acer Chromebook Spin 513 Convertible Laptop"},
 { title: "ASUS Vivobook Go 15 L510 Thin & Light Laptop Computer" },
]
```

თუ საძიებო სიტყვა იქნებოდა `acer laptop` ამ შემთხვევაში პირველი კი ჩანს ვალიდურად თუმცა თანმიმდევრობით არ წერია `acer` და `laptop`, ორივე სიტყვა შორს არის ერთმანეთისაგან. 

ახალი განახლებით #109 პირველიც ვალიდური იქნება
