### ISSUE TITLE
[BUG] Searchi brandis mixedvit ar mushaobs normalurad

### ISSUE THREAD

**Issue by Symt4xError** [educata/everrest#107]
apple-is mxolod 2 produkts agdebs searchi brandis query parametrit imitom rom mag oris obiektis brand aris "apple" da danarchenebis aris "Apple"

👍

**Comment by Symt4xError** [comment]
apple magalitad vixmare igivenairad mushaobs sxva brendebzec magalitad asus

**Comment by KostaD02** [comment]
გამოსწორდა #108
