### ISSUE TITLE
[BUG] /auth doesn't return new data

### ISSUE THREAD

**Issue by KostaD02** [educata/everrest#111]
**Describe the bug**
/auth doesn't return new data

**Expected behavior**
Auth should return new data

**Comment by CondensedMilk7** [comment]
what do you mean by new data?
Need more description.

**Comment by KostaD02** [comment]
The /auth route is returning the same data as provided by the token (just decoded and returned). The correct behavior should be to return the correct data from the database. This will make checking much easier on the frontend side and more secure in some contexts for refreshing current data in real time.

**Comment by KostaD02** [comment]
Fixed at: https://github.com/educata/everrest/commit/9f76144a11a1c34977751ba1e99a71c931f4166d
